### ISSUE TITLE
Chrome driver not detected bug

### ISSUE THREAD

**Issue by man0l** [dobizz/awbot#1]
OS: Windows

Hello,
I have downloaded manually the chrome driver and I have put it into the root folder and I still receive this error:

selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81

I have installed chrome 91 on my laptop, I believe it does not detect correctly the chrome driver.

**Comment by dobizz** [comment]
Could you paste here the path to your Google Chrome Installation? As the utils.py searches only on these directories for Windows ("C:\Program Files (x86)\Google\Chrome\Application\" and "C:\Program Files\Google\Chrome\Application\"). Thanks.
