### ISSUE TITLE
Stops after finding Mine - worked until 14-02-22

### ISSUE THREAD

**Issue by buckoii** [dobizz/awbot#5]
Was working fine but on 14-02-22 it not longer clicks the Mine  button
If Mine is manually pressed it finds claim but doesn't go any further

**Comment by jorgecruzneto** [comment]
Mine button works for me, but sometimes stop to work on claim 😭

**Comment by dobizz** [comment]
Just play around with the delays at the moment, usually it is caused when the wax blockchain is congested or the game api server itself is not responsive. So even if your are playing the game manually, you could not do so, as you will face the same problems. Right now the current version has been working for me for a few days, sometimes only a few minutes or hours.
